web:
    build: .
    links:
        - 'db'
    ports:
        - '5000:5000'
    volumes:
        - '.:/app'
    environment:
        - 'DATABASE_HOST=db'
        - 'DATABASE_NAME=postgres'
        - 'DATABASE_USER=postgres'
        - 'DATABASE_PASSWORD=postgres'
db:
    image: mongodb:9.4
    restart: always
redis:
    image: redis
    restart: always
